// Generated by CoffeeScript 1.7.1
(function() {
  var Mock, MockIrcClient, irc,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  irc = require('irc');

  Mock = require('./mockCS');

  MockIrcClient = (function(_super) {
    __extends(MockIrcClient, _super);

    function MockIrcClient() {
      MockIrcClient.__super__.constructor.call(this, irc.Client.prototype);
    }

    return MockIrcClient;

  })(Mock);

  module.exports = MockIrcClient;

}).call(this);

//# sourceMappingURL=mockIrcClientCS.map
